---
  dataSource: "prs"
  prefix: "v"
  ignoreLabels:
    - "on hold"
    - "closed"
  ignoreIssuesWith:
    - "documentation"
    - "tests"
  onlyMilestones: false
  groupBy: "label"
  changelogFilename: "CHANGELOG.md"
